#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get current time for calculating total execution time
startTime1=`date +%s`

runApplication blockMesh

endTime1=`date +%s`

mkdir 0
\cp -f 0_org/* 0/

runApplication decomposePar

# Get current time for calculating total execution time
startTime2=`date +%s`
touch sphere.foam

echo "Running parallel sdfibm with 8 processors"
mpirun -np 8 ../sdfibm/build/src/sdfibm -parallel > log.sdfibm

endTime2=`date +%s`

python3 plot_forces.py
python3 plot_residuals.py

endTime3=`date +%s`

echo "Time taken for meshing: `expr $endTime1 - $startTime1` seconds"
echo "Time taken for sdfibm execution: `expr $endTime2 - $startTime2` seconds"
echo "Total execution time: `expr $endTime3 - $startTime1` seconds"