#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get current time for calculating total execution time
startTime1=`date +%s`

runApplication blockMesh

mkdir 0
\cp -f 0_org/* 0/

runApplication decomposePar

# Get current time for calculating total execution time
startTime2=`date +%s`
touch sdfibm.foam

echo "Running parallel sdfibm with 8 processors"
mpirun -np 8 ../sdfibm/build/src/sdfibm -parallel > log.sdfibm

endTime=`date +%s`
echo "Time taken for sdfibm execution: `expr $endTime - $startTime2` seconds"
echo "Total execution time: `expr $endTime - $startTime1` seconds"

python3 plot_forces.py
python3 plot_residuals.py