#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get current time for calculating total execution time
startTime1=`date +%s`

# Get application name
application="simpleFoam"

runApplication blockMesh
runApplication snappyHexMesh -overwrite


mkdir 0
\cp -f 0_org/* 0/

runApplication potentialFoam

runApplication decomposePar

# Get current time for calculating total execution time
startTime2=`date +%s`

echo "Running parallel $application with 8 processors"
mpirun -np 8 $application -parallel > log.$application

endTime=`date +%s`
echo "Time taken for $application execution: `expr $endTime - $startTime2` seconds"
echo "Total execution time: `expr $endTime - $startTime1` seconds"